version: '3'
services:
  
  #PHP Service
  sicredi-api:
    build:
      context: .
      dockerfile: Dockerfile
    # image: digitalocean.com/php # Talvez possamos mudar isso pra uma imagem diferente?
    container_name: sicredi-api
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: sicredi-api
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
